version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  nexus:
    build: .
    ports:
      - "18081:8081"
    volumes:
      - /opt/nexus:/sonatype-work
    networks:
      - prodnetwork
    restart: always