version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  tomcat:
    build: .
    ports:
      - "18888:8080"
    volumes:  
      - /opt/tomcat:/sonatype-work
    networks:
    networks:
      - prodnetwork
    restart: always