version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  # jenkins:
  #   build: ./jenkins
  #   ports:
  #     - "18080:8080"
  #   networks:
  #     - prodnetwork
  #   volumes:
  #     - /opt/jenkins/:/var/lib/jenkins/
  #   depends_on:
  #     - gitlab
  #     - tomcat
  #     - sonar
  #   environment:
  #     - NEXUS_PORT=8081
  #     - SONAR_PORT=9000
  #     - SONAR_DB_PORT=5432

  # sonar:
  #   build: ./sonar
  #   ports:
  #     - "19000:9000"
  #     - "5432:5432"
  #   networks:
  #     - prodnetwork
  #   depends_on:
  #     - sonardb
  #   environment:
  #     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
  #     - SONARQUBE_JDBC_USERNAME=sonar
  #     - SONARQUBE_JDBC_PASSWORD=sonar

  # sonardb:
  #   networks:
  #     - prodnetwork
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #   volumes:
  #     - /opt/sonar/postgres/data:/var/lib/postgresql/data

  # tomcat:
  #   build: ./tomcat
  #   ports:
  #     - "18888:8080"
  #   volumes:  
  #     - /opt/tomcat:/sonatype-work
  #     #- /opt/tomcat/webapps:/usr/local/tomcat/webapps
  #   networks:
  #   networks:
  #     - prodnetwork
  #   restart: always

  gitlab:
    build: ./gitlab
    restart: always
    networks:
      - prodnetwork
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/data:/var/opt/gitlab

  redminedb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "redmine"
      MYSQL_DATABASE: redmine
    volumes:
      - /opt/redmine/data:/var/lib/redmine/data
    networks:
      - prodnetwork
    restart: always

  redmine:
    image: redmine:3.1.7
    ports:
      - "13000:3000"
    environment:
      REDMINE_DB_MYSQL: redminedb
      REDMINE_DB_PASSWORD: redmine
    volumes:
      - /opt/redmine/gitlab:/root
    networks:
      - prodnetwork
    depends_on:
      - redminedb
      - gitlab
    restart: always