version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  sonardb:
    networks:
      - prodnetwork
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/sonar/postgres/data:/var/lib/postgresql/data
  sonar:
    build: .
    ports:
      - "19000:9000"
      - "5432:5432"
    networks:
      - prodnetwork
    depends_on:
      - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
 